### PR TITLE
add App.addResourceFile to mobile config

### PR DESCRIPTION
**Pull request by eskan**
Add documentation related to https://github.com/meteor/meteor/pull/9748

### CODE REVIEW

**Comment by brucejo75** [comment]
Hey @eskan, any chance this can be repaired so that it shows up in the documentation?

**Comment by eskan** [comment]
Humm ... it's a pretty old PR. I've thought it was merged. I guess check failed because at build time the related PR in meteor wasn't merge so it missed a build method and tests failed.
@abernix may you launch test again or/and check merge this ?

**Comment by brucejo75** [comment]
You might be able just resubmit the PR and it will kick off the checks.

**Comment by eskan** [comment]
@brucejo75 i can't find a way to submit this PR again. Github keeps it as a reference. LEt's wait @abernix to take a look at this PR.

**Comment by brucejo75** [comment]
You can just add some inconsequential code e.g. a newline or a new comment.

Also, did you see the issues I found with [`addResourceFile`](https://github.com/meteor/meteor-feature-requests/issues/279#issuecomment-526858167)?

**Comment by eskan** [comment]
CLA signed

**Comment by filipenevola** [comment]
Hi @eskan can you update your branch with master then we can check if everything is fine? See that the deploy preview is failing. thanks

**Comment by eskan** [comment]
Hi @filipenevola , it's done.

**Comment by filipenevola** [comment]
Hi @eskan , I think something is missing, see the error message in the preview deploy process

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
4:14:01 AM: Template render error: Error: Cannot render apibox without API data: App.addResourceFile
4:14:01 AM:     at Object._prettifyError (/opt/build/repo/node_modules/nunjucks/src/lib.js:35:11)
4:14:01 AM:     at /opt/build/repo/node_modules/nunjucks/src/environment.js:547:19
4:14:01 AM:     at Template.root [as rootRenderFunc] (eval at _compile 
```

**Comment by coagmano** [comment]
Just tested this locally and it builds fine.
Does Netlify checkout the Meteor submodule correctly?
The logs indicate that it's finding the right file (`tools/cordova/builder.js`), but isn't generating the data correctly?

**Comment by eskan** [comment]
Hi @filipenevola .. same as @coagmano, it works locally. May be a netlify issue with submodule

**Pull request merged**
