### PR TITLE
Add Email.hookSend to documentation

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Add basic info about Email.hookSend which has been made public in Meteor 1.11.

### CODE REVIEW

**Review by sebakerckhof — APPROVED** [review]

**Comment by alanning** [comment]
Not familiar but here's what I've found:

Preview build added here to help keep docs + code in sync:
https://github.com/meteor/meteor/pull/9593

Perhaps the preview build doesn't run Meteor 1.11?  

These lines seem like the places to check which meteor version is being used:

```
> hexo-site@0.0.0 build /opt/build/repo
> jsdoc/jsdoc.sh && chexo meteor-hexo-config -- generate
```

Alternately, there's discussion here of it not handling submodules properly:
https://github.com/meteor/docs/pull/260

**Comment by StorytellerCZ** [comment]
After https://github.com/meteor/meteor/pull/11155 is merged, then we update the code reference here to the latest develop and this will be fine to merge.

**Comment by filipenevola** [comment]
Hey @StorytellerCZ, ready to update the code reference.

**Comment by filipenevola** [comment]
@StorytellerCZ can you check the conflict?

**Comment by StorytellerCZ** [comment]
@filipenevola Done

**Comment by lorensr** [comment]
Thank you! ☺️

**Pull request merged**
