### PR TITLE
Add querying with the sort option examples.

### PR DESCRIPTION
**Pull request by Lucasosf**
Hi guys, I'm using Meteor for quite a while.

I just want to add some examples of querying with the sort option.

What do you think?

Thanks

### CODE REVIEW

**Comment by Lucasosf** [comment]
I created this PR because I got confused when querying with some sort params.

**Comment by Lucasosf** [comment]
ping @stubailo and @glasser =)

**Comment by stubailo** [comment]
Hey, thanks for the ping! Didn't notice this one.

**Comment by Lucasosf** [comment]
Nice. Thank you =)

**Pull request merged**
