### PR TITLE
Fix Accounts hyperlinks

### PR DESCRIPTION
**Pull request by canac**
Update several broken hyperlinks to `Accounts` properties.

### CODE REVIEW

**Comment by tmeasday** [comment]
Hmm, thanks @canac but we should ensure those URLs still work as people have probably bookmarked them.

**Comment by canac** [comment]
@tmeasday Remember that none of those bookmarks won't work anyway because all of the docs URLs changed from something like http://docs.meteor.com/#/full/accounts_verifyemail to http://docs.meteor.com/api/passwords.html#Accounts-verifyEmail. It's not just the URL hash that changed; the path changed as well. I'm not saying that redirecting old bookmarked URLs isn't a good thing, I'm just saying that it will require more effort than keeping the same anchor names.

**Comment by tmeasday** [comment]
Did you try clicking on that link (http://docs.meteor.com/#/full/accounts_verifyemail) ? ;)

**Comment by tmeasday** [comment]
(it's just that those URLs (http://docs.meteor.com/#Accounts-setPassword et al) didn't get picked up I guess)

**Comment by canac** [comment]
No, I didn't, but now I see that the redirection works! I spoke too soon, and I stand corrected. Great work! 👍

**Comment by tmeasday** [comment]
Ok, I think I fixed the problem (you should see an update in a little bit)

**Comment by tmeasday** [comment]
Thanks!!

**Comment by canac** [comment]
@tmeasday Assuming I'm not overlooking something again, your change doesn't fix the original issue I was seeing: hash links on the Passwords page that don't actually go anywhere. For example, the `#accounts_emailtemplates` link needs to be changed to either `#Accounts-emailTemplates` (which will resolve to http://docs.meteor.com/api/passwords.html#Accounts-emailTemplates) or `/#/full/accounts_emailtemplates` (which will redirect to http://docs.meteor.com/api/passwords.html#Accounts-emailTemplates).

**Comment by tmeasday** [comment]
Ahh, we had a cache invalidation problem. Thanks for pointing this out.

**Pull request closed without merging**
