### PR TITLE
Replace aldeed:simple-schema with npm

### PR DESCRIPTION
**Pull request by harryadelb**
Replace aldeed:simple-schema import line with the NPM version.

### CODE REVIEW

**Comment by lorensr** [comment]
Thanks ☺️

**Comment by harryadelb** [comment]
No, thank you for you quick response! :) A side question, are you in charge of merging the guide PRs too?

**Comment by lorensr** [comment]
Welcome 🤗 One of the people, although I'm not putting much time into it
these days

**Comment by harryadelb** [comment]
I see. Anyway, thanks and keep up the good work. :)

**Pull request merged**
